name: mehran_football_academy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  supabase_flutter: ^2.8.4
  google_nav_bar: ^5.0.7
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  http: ^1.3.0
  timeago: ^3.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  connectivity_plus: ^6.1.3
  image: ^4.5.3
  path: ^1.9.1
  file_picker: ^9.1.0
  video_player: ^2.9.3
  shared_preferences: ^2.5.2
  flutter_cache_manager: ^3.4.1
  app_links: ^6.4.0
  fl_chart: ^0.71.0
  cached_network_image: ^3.4.1
  firebase_core: ^3.13.0
  onesignal_flutter: ^5.3.2
  firebase_messaging: ^15.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.13
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/splash.png
    - assets/lottiefile.json
    - assets/assister.json
    - assets/running.json
    - assets/mtm.json
    - assets/scorer.json
    - assets/logo1.png
    - assets/password.png
    - assets/image1.jpg
    - assets/image2.jpg
    - assets/image3.jpg
    - assets/image4.jpg
    - assets/image5.jpg
    - assets/profile.jpg
    - assets/background.jpg

  fonts:
    - family: RubikMedium
      fonts:
        - asset: assets/Rubik-Medium.ttf
    - family: RubikRegular
      fonts:
        - asset: assets/Rubik-Regular.ttf